Repository wecode-bootcamp-korea/19-1st-Market-ChoKurly-frontend, pull requests merged in 2021-04, with the labels that each got.

#3 [19기 채준형]회원가입 페이지 - 기능구현완료 (컴포넌트 분리는 미실시)
  package-lock.json
  package.json
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Signup/Check.js
  src/Pages/Signup/Id.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Routes.js
  src/Styles/common.scss
  src/index.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#9 [19기 채준형] 페이지 충돌해결을 위한 Routes수정완료
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#4 [19기 채준형]회원가입 완료 페이지-충돌해결을 위한 수정 및 리뷰반영
  src/Pages/Login/Login.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/SignupFin/SignupFin.js
  src/Pages/Signup/SignupFin/SignupFin.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#6 [19기 이예원] Main: 페이지 레이아웃, 필수 기능 구현 완료
  public/data/bannerSlide.json
  public/data/mdtags.json
  public/data/productCard_main.json
  public/data/productCard_main2.json
  public/images/Main/limited.jpg
  public/images/Slide/donuts.jpg
  public/images/Slide/icecream.jpg
  public/images/Slide/macarons.jpg
  public/images/Slide/marsh.jpg
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/FooterIconData.js
  src/Components/Footer/FooterInfoData.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/TopBtn/TopBtn.js
  src/Components/TopBtn/TopBtn.scss
  src/Pages/Login/Login.scss
  src/Pages/Main/Components/Category.js
  src/Pages/Main/Components/Category.scss
  src/Pages/Main/Components/LimitedEvent/LimitedEvent.js
  src/Pages/Main/Components/LimitedEvent/LimitedEvent.scss
  src/Pages/Main/Components/ProductCard/ProductCard.js
  src/Pages/Main/Components/ProductCard/ProductCard.scss
  src/Pages/Main/Components/ProductCardSlide/ProductCardSlide.js
  src/Pages/Main/Components/ProductCardSlide/ProductCardSlide.scss
  src/Pages/Main/Components/Slide/Slide.js
  src/Pages/Main/Components/Slide/Slide.scss
  src/Pages/Main/Components/Tag/Tag.js
  src/Pages/Main/Components/Tag/Tag.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Signup/Check.js
  src/Pages/Signup/Id.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Pages/Signup/SignupFin/SignupFin.js
  src/Pages/Signup/SignupFin/SignupFin.scss
  src/Styles/common.scss
Labels: Status: Conflict 발생, Status: 리뷰 요청, Status: 수정 요청, Status: 추가 기능 구현중

#5 [19기 서동이] 상세페이지 기능구현 완료
  Icon 
  package-lock.json
  package.json
  public/data/ThumbnailData.json
  public/images/macachoco.jpg
  public/images/ribonchoco.jpg
  public/images/timtam.png
  public/images/상세페이지 썸네일.jpg
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Pages/Cart/Cart.js
  src/Pages/ProductDetails/Components/GoodsDetails/Components/GoodsDescription/GoodsDescription.js
  src/Pages/ProductDetails/Components/GoodsDetails/Components/GoodsDescription/GoodsDescription.scss
  src/Pages/ProductDetails/Components/GoodsDetails/Components/MoreInformation/MoreInfoData.js
  src/Pages/ProductDetails/Components/GoodsDetails/Components/MoreInformation/MoreInformation.js
  src/Pages/ProductDetails/Components/GoodsDetails/Components/MoreInformation/MoreInformation.scss
  src/Pages/ProductDetails/Components/GoodsDetails/GoodsDetails.js
  src/Pages/ProductDetails/Components/GoodsDetails/GoodsDetails.scss
  src/Pages/ProductDetails/Components/GuestReview/GuestReview.js
  src/Pages/ProductDetails/Components/GuestReview/GuestReview.scss
  src/Pages/ProductDetails/Components/GuestReview/GuestReviewData.js
  src/Pages/ProductDetails/Components/QuantityBtn/QuantityBtn.js
  src/Pages/ProductDetails/Components/QuantityBtn/QuantityBtn.scss
  src/Pages/ProductDetails/Components/RelatedProducts/RelatedProduct.js
  src/Pages/ProductDetails/Components/RelatedProducts/RelatedProduct.scss
  src/Pages/ProductDetails/Components/Taps/Taps.js
  src/Pages/ProductDetails/Components/Taps/Taps.scss
  src/Pages/ProductDetails/Components/Thumbnail/Thumbnail.js
  src/Pages/ProductDetails/Components/Thumbnail/Thumbnail.scss
  src/Pages/ProductDetails/ProductDetails.js
  src/Pages/ProductDetails/ProductDetails.scss
  src/Pages/ProductList/ProductList.js
  src/Routes.js
  src/Styles/reset.scss
  src/config.js
  src/index.js
Labels: Status: 수정 요청, Status: 추가 기능 구현중

#11 [19기 채준형]로그인페이지 기능구현 및 서브페이지(아이디 찾기, 비밀번호 찾기)기능구현 완료
  src/Pages/Login/Find/Findid.js
  src/Pages/Login/Find/Findid.scss
  src/Pages/Login/Find/Findpw.js
  src/Pages/Login/Find/Findpw.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Routes.js
Labels: Status: Conflict 발생, Status: 리뷰 요청

#15 [19기 채준형]장바구니 페이지 기능구현 완료
  public/data/cartdata.json
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/OrderList/OrderList.js
  src/Pages/Cart/OrderList/OrderList.scss
  src/Pages/Login/Find/Findid.js
  src/Pages/Login/Find/Findid.scss
  src/Pages/Login/Find/Findpw.js
  src/Pages/Login/Find/Findpw.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/Components/ProductCard/ProductCard.scss
  src/Pages/Main/Components/Slide/Slide.scss
  src/Pages/ProductDetails/Components/GoodsDetails/Components/GoodsDescription/GoodsDescription.scss
  src/Pages/ProductDetails/Components/GuestReview/GuestReview.scss
  src/Pages/ProductDetails/Components/RelatedProducts/RelatedProduct.js
  src/Pages/ProductDetails/Components/Thumbnail/Thumbnail.js
  src/Pages/ProductDetails/Components/Thumbnail/Thumbnail.scss
  src/Pages/ProductList/Components/ProductCard.scss
  src/Routes.js
  src/Styles/common.scss
  src/config.js
  src/index.js
Labels: Status: 리뷰 요청

#12 [19기 이예원] Main: 라우팅/데이터 호출 테스트 완료
  public/data/mdtags.json
  public/data/productCard.json
  public/data/productCard_main.json
  public/data/productCard_main2.json
  public/data/tags.json
  src/Components/Nav/Components/Category.js
  src/Pages/Main/Components/ProductCard/ProductCard.js
  src/Pages/Main/Components/ProductCard/ProductCard.scss
  src/Pages/Main/Components/ProductCardSlide/ProductCardSlide.scss
  src/Pages/Main/Components/Slide/Slide.scss
  src/Pages/Main/Components/Tag/Tag.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Routes.js
Labels: Status: Conflict 발생
